import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css'
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DAMC | BEST REAL ESTATE IN DUBAI | PREMIMUM REAL ESTATE IN DUBI ",
  description: "Generated by create next app",
  icons:{
    icon:'/building.jpg'
      }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bgimage">
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
